name: DEEPSEA
hyperparameters:
    dataset: DEEPSEA
    embedder_dataset: text
    objective: otdd-exact
    weight: roberta
    maxsamples: 64
    ep_tune_start: 60
    freeze: False

    arch: roberta
    experiment_id: 0
    epochs: 25 
    finetune_method: all
    seed: 0
    
    batch_size: 16 
    eval_batch_size: 1000
    accum: 32
    clip: -1 
    validation_freq: 1

    optimizer:
        name: AdamW
        params:
            lr: 0.0001 #
            betas: [0.9, 0.98] #
            weight_decay: 0.000001 
            momentum: 0.99

    encoder_optimizer:
        name: AdamW
        params:
            lr: 0.0001
            betas: [0.9, 0.98]
            weight_decay: 0.000001
            momentum: 0.99
    
    scheduler:  
        name: WarmupLR
        params:
            warmup_epochs: 5
            decay_epochs: 100
            sched: [20, 40, 60]
            base: 0.2

    encoder_scheduler:  
        name: StepLR
        params:
            warmup_epochs: 10
            decay_epochs: 100
            sched: [20, 40, 60]
            base: 0.2

    num_workers: 4
    reproducibility: False
    valid_split: False

min_validation_period:
    epochs: 1
bind_mounts:
    - host_path: /tmp
      container_path: /data
    - host_path: /tmp
      container_path: /root/.cache
resources:
  slots_per_trial: 1
records_per_epoch: 9281
searcher:
  name:  single
  metric: accuracy
  smaller_is_better: false
  max_length:
    epochs: 1
max_restarts: 0
entrypoint: python3 -W ignore main.py