name: MUSIC-JSB
hyperparameters:
    dataset: MUSIC-JSB 
    embedder_dataset: text
    objective: otdd-exact
    weight: roberta
    maxsamples: 64 
    ep_tune_start: 60
    freeze: False

    experiment_id: 0
    epochs: 60
    finetune_method: all
    seed: 0

    batch_size: 8
    eval_batch_size: 1000
    accum: 1
    clip: -1 
    validation_freq: 1

    optimizer:
        name: SGD #
        params:
            lr: 0.01 
            betas: [0.9, 0.98]
            weight_decay: 0.0 
            momentum: 0.9

    encoder_optimizer:
        name: SGD
        params:
            lr: 0.01
            betas: [0.9, 0.98]
            weight_decay: 0.0
            momentum: 0.9
    
    scheduler:  
        name: WarmupLR
        params:
            warmup_epochs: 5
            decay_epochs: 100
            sched: [20, 40, 60]
            base: 0.2

    encoder_scheduler:  
        name: StepLR
        params:
            warmup_epochs: 10
            decay_epochs: 60
            sched: [20, 40, 60]
            base: 0.2

    num_workers: 4
    reproducibility: False
    valid_split: False

min_validation_period:
    epochs: 1
bind_mounts:
    - host_path: /tmp
      container_path: /data
    - host_path: /tmp
      container_path: /root/.cache
resources:
  slots_per_trial: 1
records_per_epoch: 50000
searcher:
  name:  single
  metric: accuracy
  smaller_is_better: false
  max_length:
    epochs: 1
max_restarts: 0
entrypoint: python3 -W ignore main.py